#ifndef STATES_H
#define STATES_H

typedef enum {
	SUCCESS = 0,
	FAILURE,
	ERROR_NULL_POINTER,
	ERROR_OUT_OF_MEMORY,
	ERROR_FILE_NOT_FOUND,
	ERROR_FILE_LOAD,
	ERROR_INVALID_PARAMETER,
	ERROR_SHADER_CREATION,
	ERROR_SHADER_COMPILATION,
	ERROR_SHADER_PROGRAM_CREATION,
	ERROR_PROGRAM_LINKING,
	ERROR_UNKNOWN
} State;

typedef enum {
	OPENGL = 0,
	VULKAN,
	SOFTWARE
} RenderBackend;

#endif // STATES_H
